name: cd
on:
  push:
    tags:
      - "v*"

jobs:
  plugin-cd:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-cd.yml@6e3b523f38c8286c412fe5bef5261841e82f9dc7
    secrets: inherit
