name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  plugin-ci:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-ci.yml@6e3b523f38c8286c412fe5bef5261841e82f9dc7
    secrets: inherit
